MODULES+=       redis

MODULE_SUMMARY_redis=   3rd-party http_redis dynamic module

MODULE_CONTRIB_DEPS_redis=      ngx_http_redis

include $(foreach dep,$(MODULE_CONTRIB_DEPS_redis),$(CONTRIB)/src/$(dep)/version)

MODULE_VERSION_redis=   $(NGX_HTTP_REDIS_VERSION)
MODULE_RELEASE_redis=   3

MODULE_VERSION_PREFIX_redis=$(MODULE_TARGET_PREFIX)

MODULE_SOURCES_redis=   ngx_http_redis-$(NGX_HTTP_REDIS_VERSION).tar.gz

MODULE_CONFARGS_redis=  --add-dynamic-module=$(MODSRC_PREFIX)ngx_http_redis-$(NGX_HTTP_REDIS_VERSION)

MODULE_CC_OPT_redis=-DREDIS_SET_VAR -DREDIS_UPSTREAM_LIST
MODULE_CC_OPT_DEBUG_redis=$(MODULE_CC_OPT_redis)

ifeq ($(MODULE_TARGET), plus)
REDIS_DEPENDENCY_TAG=   nginx-plus-module-redis-r$(PLUS_VERSION)
else
REDIS_DEPENDENCY_TAG=   nginx-module-redis-r$(BASE_VERSION)
endif

define MODULE_POST_redis
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_redis) for $(MODULE_SUMMARY_PREFIX) has been installed.
To enable this module, add the following to /etc/nginx/nginx.conf
and reload nginx:

    load_module modules/ngx_http_redis_module.so;

Please refer to the module documentation for further details:
https://github.com/osokin/ngx_http_redis

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_redis
